# Generated by Django 4.1.7 on 2023-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errorlog',
            fields=[
                ('err', models.CharField(max_length=125, primary_key=True, serialize=False, verbose_name='错误信息')),
                ('num', models.SmallIntegerField(verbose_name='次数')),
                ('txt', models.CharField(max_length=225, verbose_name='解决办法')),
            ],
        ),
    ]
