# Generated by Django 4.1.7 on 2023-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='err',
            field=models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='错误信息'),
        ),
    ]
